"""Add user_id column to Exercise

Revision ID: 2159134a5182
Revises: a6e8b26cc7bf
Create Date: 2026-08-04 13:59:43.526952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2159134a5182'
down_revision: Union[str, Sequence[str], None] = 'a6e8b26cc7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
