"""Addedd cascade delete in Type and Category

Revision ID: 72aa0a7ad4b3
Revises: 5008a98f3836
Create Date: 2026-07-09 16:46:46.827530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72aa0a7ad4b3'
down_revision: Union[str, Sequence[str], None] = '5008a98f3836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
